# Root directory of the project
root = "."

# Command to run the application
cmd = "go run ./cmd/homesystem"

# Directory to temporarily store compiled binaries
tmp_dir = "tmp"

# File extensions to watch for changes
include_ext = ["go"]

# Directories to exclude from watching
exclude_dir = ["vendor", "tmp", "logs"]

# Files to exclude from watching
exclude_file = ["air.toml"]

# Delay in seconds before restarting the application after a file change
# delay = 500

# If true, Air will not print colored logs
no_color = false

[build]
cmd = "go build -o ./tmp/main ./cmd/homesystem"
bin = "./tmp/main"


# # Define directories of the project
# root = "."
# tmp_dir = "tmp"

# #
# bin = "go"

# # Define the main package of the project
# cmd = "go run cmd/homesystem"

# include_ext = ["go", "tpl", "tmpl", "html"]

# [build]
# cmd = "go build -o main ."
# bin = "main"

# [log]
# time = true
